services:
  spam-filter:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    pull_policy: build
    ports:
      - ${TELEGRAM_WEBHOOK_PORT:-8443}:${TELEGRAM_WEBHOOK_PORT:-8443}
    environment:
      - REACT_NON_SPAM=${REACT_NON_SPAM}
      - DELETE_SPAM=${DELETE_SPAM}
      - LLM_ENDPOINT=${LLM_ENDPOINT}
      - LLM_API_KEY=${LLM_API_KEY}
      - SYSTEM_PROMPT=${SYSTEM_PROMPT}
      - MODEL=${MODEL}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_IDS=${TELEGRAM_CHAT_IDS}
      - TELEGRAM_WEBHOOK_DOMAIN=${TELEGRAM_WEBHOOK_DOMAIN}
      - TELEGRAM_WEBHOOK_PORT=${TELEGRAM_WEBHOOK_PORT:-8443}